services:
  web:
    build:
      context: blog
      target: dev-envs
    ports:
      - 4200:4200
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./blog:/project_sessao2
      - /project_sessao2/node_modules
